##### $Name:\,\color{blue}{Bin\,Lu,\,Maymoonah\,Bashir,\,Christopher\,J.\,Watson}$
##### $School:\,\color{blue}{Marcos\,School\,of\,Engineering,\,University\,of\,San\,Diego}$
##### $Class:\,\color{blue}{AAI\,500-\,Probability\,\&\,Stats\,for\,AI}$
##### $Assignment:\,\color{blue}{MSAAI\,Final Project-Make\,and\,Model}$
##### $Date:\,\color{blue}{10/22/2022}$

### Problem - Make and Model Handling

Statement - The problem with make and model was that they weren't very usable in their current state. We had many choices for regression, but for most of our predictions with categorical data we wanted to use the One Hot Code approach. This would be impractical for how many different make and models there were. 
$\newline$
1) The Make is almost superceeded by the Model in terms of defining a category. For this we merged the two columns
$\newline$
2) We decided that average mean would be a better representation categorically for the Model column.

In [27]:
# Importing important libraries
import numpy as np
import pandas as pd
import data_utils_g1 as du

# Get Path
path = 'C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/FilterData.csv'

# Reading the dataset
data = pd.read_csv(path)

# Show sample of the dataset
display(data.head(10))

,Unnamed: 0,ID,Price,Levy,Manufacturer,Model,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
0,0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,NaN,186005,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12
1,1,44731507,16621,1018,CHEVROLET,EQUINOX,2011,Jeep,No,Petrol,3.0,NaN,192000,6,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
2,2,45774419,8467,0,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,NaN,200000,4,Variator,Front,4-5,Right-hand drive,Black,2
3,3,45769185,3607,862,FORD,ESCAPE,2011,Jeep,Yes,Hybrid,2.5,NaN,168966,4,Automatic,Front-Rear,4-5,Left wheel,White,0
4,4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,NaN,91901,4,Automatic,Front,4-5,Left wheel,Silver,4
5,5,45802912,39493,891,HYUNDAI,SANTA FE,2016,Jeep,Yes,Diesel,2.0,NaN,160931,4,Automatic,Front,4-5,Left wheel,White,4
6,6,45656768,1803,761,TOYOTA,PRIUS,2010,Hatchback,Yes,Hybrid,1.8,NaN,258909,4,Automatic,Front,4-5,Left wheel,White,12
7,7,45816158,549,751,HYUNDAI,SONATA,2013,Sedan,Yes,Petrol,2.4,NaN,216118,4,Automatic,Front,4-5,Left wheel,Grey,12
8,8,45641395,1098,394,TOYOTA,CAMRY,2014,Sedan,Yes,Hybrid,2.5,NaN,398069,4,Automatic,Front,4-5,Left wheel,Black,12
9,9,45756839,26657,0,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,NaN,128500,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12

First, we need to combine the two columns. This can be a simple set of column manipulations

In [29]:
# Make new column
data_combo = data['Manufacturer'] + '-' + data['Model']

# Make a copy to preserve original for re-run purposes
data2 = data.copy()

# Insert out new column
data2.insert(loc = 4,
          column = 'MakeModel',
          value = data_combo)

# Drop old columns
data2.drop(['Manufacturer', 'Model'], axis=1, inplace=True)

# Show sample of the dataset
display(data2.head(10))

,Unnamed: 0,ID,Price,Levy,MakeModel,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
0,0,45654403,13328,1399,LEXUS-RX 450,2010,Jeep,Yes,Hybrid,3.5,NaN,186005,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12
1,1,44731507,16621,1018,CHEVROLET-EQUINOX,2011,Jeep,No,Petrol,3.0,NaN,192000,6,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
2,2,45774419,8467,0,HONDA-FIT,2006,Hatchback,No,Petrol,1.3,NaN,200000,4,Variator,Front,4-5,Right-hand drive,Black,2
3,3,45769185,3607,862,FORD-ESCAPE,2011,Jeep,Yes,Hybrid,2.5,NaN,168966,4,Automatic,Front-Rear,4-5,Left wheel,White,0
4,4,45809263,11726,446,HONDA-FIT,2014,Hatchback,Yes,Petrol,1.3,NaN,91901,4,Automatic,Front,4-5,Left wheel,Silver,4
5,5,45802912,39493,891,HYUNDAI-SANTA FE,2016,Jeep,Yes,Diesel,2.0,NaN,160931,4,Automatic,Front,4-5,Left wheel,White,4
6,6,45656768,1803,761,TOYOTA-PRIUS,2010,Hatchback,Yes,Hybrid,1.8,NaN,258909,4,Automatic,Front,4-5,Left wheel,White,12
7,7,45816158,549,751,HYUNDAI-SONATA,2013,Sedan,Yes,Petrol,2.4,NaN,216118,4,Automatic,Front,4-5,Left wheel,Grey,12
8,8,45641395,1098,394,TOYOTA-CAMRY,2014,Sedan,Yes,Hybrid,2.5,NaN,398069,4,Automatic,Front,4-5,Left wheel,Black,12
9,9,45756839,26657,0,LEXUS-RX 350,2007,Jeep,Yes,Petrol,3.5,NaN,128500,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12

In [32]:
# get all unique make-model combos
categoryarray = data2.MakeModel.unique()

# loop and query required mean information
pricemeanarray = []
pricesdarray = []
for x in categoryarray:
    comm = "MakeModel == '"+x+"'"
    df = data2.query(comm)
    price = df['Price']
    mean = price.mean()
    sd = price.std()
    pricemeanarray.append(round(mean,2))
    pricesdarray.append(round(sd,2))

# convert to numpy array
npArray = np.array(pricemeanarray)
# show values
print(npArray.min())
print(npArray.max())
print(len(categoryarray))

34.0
297930.0
1490

In [38]:
small = (npArray-npArray.min())/npArray.max()

replace_table = {'Value':small,'MakeModel':categoryarray}
replace_table = pd.DataFrame(replace_table)
# Show sample of the dataset
display(replace_table.head(10))

      Value            MakeModel
0  0.035710         LEXUS-RX 450
1  0.029261    CHEVROLET-EQUINOX
2  0.037106            HONDA-FIT
3  0.027494          FORD-ESCAPE
4  0.133393     HYUNDAI-SANTA FE
5  0.038329         TOYOTA-PRIUS
6  0.048425       HYUNDAI-SONATA
7  0.042147         TOYOTA-CAMRY
8  0.055940         LEXUS-RX 350
9  0.033829  MERCEDES-BENZ-E 350

In [43]:
result = data2.replace(dict(zip(replace_table.MakeModel, replace_table.Value)))

display(result.head(10))

,Unnamed: 0,ID,Price,Levy,MakeModel,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
0,0,45654403,13328,1399,0.035710,2010,Jeep,Yes,Hybrid,3.5,NaN,186005,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12
1,1,44731507,16621,1018,0.029261,2011,Jeep,No,Petrol,3.0,NaN,192000,6,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
2,2,45774419,8467,0,0.037106,2006,Hatchback,No,Petrol,1.3,NaN,200000,4,Variator,Front,4-5,Right-hand drive,Black,2
3,3,45769185,3607,862,0.027494,2011,Jeep,Yes,Hybrid,2.5,NaN,168966,4,Automatic,Front-Rear,4-5,Left wheel,White,0
4,4,45809263,11726,446,0.037106,2014,Hatchback,Yes,Petrol,1.3,NaN,91901,4,Automatic,Front,4-5,Left wheel,Silver,4
5,5,45802912,39493,891,0.133393,2016,Jeep,Yes,Diesel,2.0,NaN,160931,4,Automatic,Front,4-5,Left wheel,White,4
6,6,45656768,1803,761,0.038329,2010,Hatchback,Yes,Hybrid,1.8,NaN,258909,4,Automatic,Front,4-5,Left wheel,White,12
7,7,45816158,549,751,0.048425,2013,Sedan,Yes,Petrol,2.4,NaN,216118,4,Automatic,Front,4-5,Left wheel,Grey,12
8,8,45641395,1098,394,0.042147,2014,Sedan,Yes,Hybrid,2.5,NaN,398069,4,Automatic,Front,4-5,Left wheel,Black,12
9,9,45756839,26657,0,0.055940,2007,Jeep,Yes,Petrol,3.5,NaN,128500,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12

In [45]:
result.sort_values(by=['ID'])
training = result.head(13453)
test = result.tail(5764).head(2882)
validation = result.tail(2882)

In [46]:
training.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/TrainingData2.csv',index=False,line_terminator='\n')
test.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/TestData2.csv',index=False,line_terminator='\n')
validation.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/ValidationData2.csv',index=False,line_terminator='\n')

As shown in the box plot above there is at least 1 super outlier that completely harms the data. Using a systematic attempt it was removed.

As we can see from the table and the box plot, although there are still outliers, the ones that massively skewed the data have been removed. In my opinion, more could have been removed from the bottom but we decided that it would be even on both the left and the right sides of the data. 
$\newline$
Upper percentile from base data = 0.99985
$\newline$
Lower percentile from base data = 0.00015
$\newline$
### In conclusion, this removal was required to make an accurate model for suggesting what a costumer should sell their car for in the market.