##### $Name:\,\color{blue}{Bin\,Lu,\,Maymoonah\,Bashir,\,Christopher\,J.\,Watson}$
##### $School:\,\color{blue}{Marcos\,School\,of\,Engineering,\,University\,of\,San\,Diego}$
##### $Class:\,\color{blue}{AAI\,500-\,Probability\,\&\,Stats\,for\,AI}$
##### $Assignment:\,\color{blue}{MSAAI\,Final Project-Make\,and\,Model}$
##### $Date:\,\color{blue}{10/22/2022}$

### Problem - Make and Model Handling

Statement - The problem with make and model was that they weren't very usable in their current state. We had many choices for regression, but for most of our predictions with categorical data we wanted to use the One Hot Code approach. This would be impractical for how many different make and models there were. 
$\newline$
1) The Make is almost superceeded by the Model in terms of defining a category. For this we merged the two columns
$\newline$
2) We decided that average mean would be a better representation categorically for the Model column.

In [27]:
# Importing important libraries
import numpy as np
import pandas as pd
import data_utils_g1 as du

# Get Path
path = 'C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/FilterData.csv'

# Reading the dataset
data = pd.read_csv(path)

# Show sample of the dataset
display(data.head(10))

,Unnamed: 0,ID,Price,Levy,Manufacturer,Model,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
0,0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,NaN,186005,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12
1,1,44731507,16621,1018,CHEVROLET,EQUINOX,2011,Jeep,No,Petrol,3.0,NaN,192000,6,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
2,2,45774419,8467,0,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,NaN,200000,4,Variator,Front,4-5,Right-hand drive,Black,2
3,3,45769185,3607,862,FORD,ESCAPE,2011,Jeep,Yes,Hybrid,2.5,NaN,168966,4,Automatic,Front-Rear,4-5,Left wheel,White,0
4,4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,NaN,91901,4,Automatic,Front,4-5,Left wheel,Silver,4
5,5,45802912,39493,891,HYUNDAI,SANTA FE,2016,Jeep,Yes,Diesel,2.0,NaN,160931,4,Automatic,Front,4-5,Left wheel,White,4
6,6,45656768,1803,761,TOYOTA,PRIUS,2010,Hatchback,Yes,Hybrid,1.8,NaN,258909,4,Automatic,Front,4-5,Left wheel,White,12
7,7,45816158,549,751,HYUNDAI,SONATA,2013,Sedan,Yes,Petrol,2.4,NaN,216118,4,Automatic,Front,4-5,Left wheel,Grey,12
8,8,45641395,1098,394,TOYOTA,CAMRY,2014,Sedan,Yes,Hybrid,2.5,NaN,398069,4,Automatic,Front,4-5,Left wheel,Black,12
9,9,45756839,26657,0,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,NaN,128500,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12

First, we need to combine the two columns. This can be a simple set of column manipulations

In [29]:
# Make new column
data_combo = data['Manufacturer'] + '-' + data['Model']

# Make a copy to preserve original for re-run purposes
data2 = data.copy()

# Insert out new column
data2.insert(loc = 4,
          column = 'MakeModel',
          value = data_combo)

# Drop old columns
data2.drop(['Manufacturer', 'Model'], axis=1, inplace=True)

# Show sample of the dataset
display(data2.head(10))

,Unnamed: 0,ID,Price,Levy,MakeModel,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
0,0,45654403,13328,1399,LEXUS-RX 450,2010,Jeep,Yes,Hybrid,3.5,NaN,186005,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12
1,1,44731507,16621,1018,CHEVROLET-EQUINOX,2011,Jeep,No,Petrol,3.0,NaN,192000,6,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
2,2,45774419,8467,0,HONDA-FIT,2006,Hatchback,No,Petrol,1.3,NaN,200000,4,Variator,Front,4-5,Right-hand drive,Black,2
3,3,45769185,3607,862,FORD-ESCAPE,2011,Jeep,Yes,Hybrid,2.5,NaN,168966,4,Automatic,Front-Rear,4-5,Left wheel,White,0
4,4,45809263,11726,446,HONDA-FIT,2014,Hatchback,Yes,Petrol,1.3,NaN,91901,4,Automatic,Front,4-5,Left wheel,Silver,4
5,5,45802912,39493,891,HYUNDAI-SANTA FE,2016,Jeep,Yes,Diesel,2.0,NaN,160931,4,Automatic,Front,4-5,Left wheel,White,4
6,6,45656768,1803,761,TOYOTA-PRIUS,2010,Hatchback,Yes,Hybrid,1.8,NaN,258909,4,Automatic,Front,4-5,Left wheel,White,12
7,7,45816158,549,751,HYUNDAI-SONATA,2013,Sedan,Yes,Petrol,2.4,NaN,216118,4,Automatic,Front,4-5,Left wheel,Grey,12
8,8,45641395,1098,394,TOYOTA-CAMRY,2014,Sedan,Yes,Hybrid,2.5,NaN,398069,4,Automatic,Front,4-5,Left wheel,Black,12
9,9,45756839,26657,0,LEXUS-RX 350,2007,Jeep,Yes,Petrol,3.5,NaN,128500,6,Automatic,Front-Rear,4-5,Left wheel,Silver,12

Next, we need to mean all the various cars by MakeModel set values

In [49]:
# get all unique make-model combos
categoryarray = data2.MakeModel.unique()

# loop and query required mean information
pricemeanarray = []
pricesdarray = []
for x in categoryarray:
    comm = "MakeModel == '"+x+"'"
    df = data2.query(comm)
    price = df['Price']
    mean = price.mean()
    sd = price.std()
    pricemeanarray.append(round(mean,2))
    pricesdarray.append(round(sd,2))

# convert to numpy array
npArray = np.array(pricemeanarray)

Then, we make the values easy to use by scaling them between 0 and 1

In [50]:
# show values
print('The minimum average of any MakeModel is:', npArray.min())
print('The maximum average of any MakeModel is:', npArray.max())
print('The number of MakeModel uniques is:', len(categoryarray))

The minimum average of any MakeModel is: 34.0
The maximum average of any MakeModel is: 297930.0
The number of MakeModel uniques is: 1490

Finally, we create a lookup table and do replacements into a final dataframe

In [51]:
# formula to convert all average values from 0 to 1
replace_weight = (npArray-npArray.min())/npArray.max()

# create lookup table
replace_table = {'Value':replace_weight,'MakeModel':categoryarray}
replace_table = pd.DataFrame(replace_table)

# Show sample of the dataset
display(replace_table.head(10))

      Value            MakeModel
0  0.035710         LEXUS-RX 450
1  0.029261    CHEVROLET-EQUINOX
2  0.037106            HONDA-FIT
3  0.027494          FORD-ESCAPE
4  0.133393     HYUNDAI-SANTA FE
5  0.038329         TOYOTA-PRIUS
6  0.048425       HYUNDAI-SONATA
7  0.042147         TOYOTA-CAMRY
8  0.055940         LEXUS-RX 350
9  0.033829  MERCEDES-BENZ-E 350

In [74]:
# replace values from lookuptable
result = result.replace( 'Turbo', 1.7554345902046502)
result['Turbo'] = result['Turbo'].fillna(1)

# Show sample of the dataset
display(result.head(20))

,Unnamed: 0,ID,Price,Levy,MakeModel,Prod_year,Category,Leather_interior,Fuel_type,Engine_volume,Turbo,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags
11207,11219,20746880,157,0,0.046772,1939,Limousine,Yes,Petrol,2.4,1,126000,4,Automatic,Rear,4-5,Left wheel,White,0
13212,13225,23242980,200,0,0.141307,2017,Jeep,Yes,Petrol,2.7,1,95000,4,Automatic,Front-Rear,5,Left wheel,Black,10
13558,13572,24367759,85702,0,0.299423,2013,Microbus,Yes,Diesel,2.2,1.7554345902046502,225000,6,Manual,Rear,2-3,Left wheel,White,4
3640,3643,24701923,130,0,0.058867,2006,Jeep,Yes,Petrol,4.4,1,90000,8,Tiptronic,Front-Rear,4-5,Left wheel,Black,8
5504,5509,24940334,25089,0,0.057150,1999,Limousine,Yes,Petrol,5.4,1,99000,8,Automatic,Front-Rear,4-5,Left wheel,White,4
19041,19061,25368573,12544,0,0.029406,2002,Sedan,Yes,CNG,2.5,1,220000,6,Tiptronic,Rear,4-5,Left wheel,Silver,8
11412,11424,26248496,150,0,0.081655,2012,Microbus,Yes,Diesel,3.2,1.7554345902046502,200000,6,Manual,Rear,4-5,Left wheel,Silver,2
15835,15852,26327387,87021,0,0.299423,2013,Microbus,Yes,Diesel,2.2,1.7554345902046502,240000,8,Manual,Rear,4-5,Left wheel,White,2
14948,14964,26465408,43000,0,0.041607,2011,Jeep,Yes,Diesel,3.0,1,190000,6,Tiptronic,Front-Rear,4-5,Left wheel,Grey,12
10254,10265,26556126,157,0,0.000485,1939,Cabriolet,Yes,Petrol,5.0,1,129000,8,Automatic,Rear,4-5,Left wheel,Silver,0
14140,14154,26556811,60,0,0.038329,2012,Hatchback,Yes,Hybrid,1.8,1,100000,4,Automatic,Front,4-5,Left wheel,Silver,12
2490,2493,28135943,3136,0,0.019542,1998,Sedan,Yes,Petrol,2.8,1,299689,6,Tiptronic,Front,4-5,Left wheel,Silver,6
4466,4469,28548396,5000,0,0.027766,2004,Universal,No,Diesel,2.2,1.7554345902046502,312000,4,Automatic,Front,4-5,Left wheel,Black,4
9490,9500,29267633,120,0,0.039800,2003,Sedan,Yes,Petrol,3.2,1,130000,6,Tiptronic,Rear,4-5,Left wheel,Black,8
14915,14931,30551412,370,0,0.174190,2018,Jeep,Yes,Petrol,4.0,1,15000,8,Automatic,Front-Rear,4-5,Left wheel,Black,12
8046,8054,30601481,150,0,0.000389,2010,Sedan,Yes,Petrol,5.5,1,15000,8,Tiptronic,Front-Rear,4-5,Left wheel,Black,12
9874,9885,31756996,18660,382,0.052501,2014,Sedan,Yes,Hybrid,2.4,1,114000,4,Automatic,Front,4-5,Left wheel,Blue,10
12320,12333,31881664,3700,0,0.092797,2001,Sedan,Yes,Diesel,2.2,1,0,4,Automatic,Rear,4-5,Right-hand drive,Blue,4
11146,11158,32089280,50,0,0.056752,2012,Sedan,No,Hybrid,1.5,1,150000,2,Automatic,Rear,4-5,Right-hand drive,Blue,0
252,253,32116317,50,0,0.056752,2013,Sedan,No,Hybrid,1.5,1,130000,4,Automatic,Rear,4-5,Right-hand drive,Sky blue,0

In [73]:
combo = result['Turbo'].astype(float) * result['Engine_volume'].astype(float)
display(combo)

11207    2.400000
13212    2.700000
13558    3.861956
3640     4.400000
5504     5.400000
           ...
14869    2.000000
709      1.800000
2165     1.800000
12232    3.510869
358      2.400000
Length: 19217, dtype: float64

In [75]:
# Drop old columns
result.drop(['Manufacturer', 'Model'], axis=1, inplace=True)

# Insert out new column
result.insert(loc = 10,
          column = 'Engine_volume',
          value = combo)

display(result.head(20))

KeyError: "['Manufacturer', 'Model'] not found in axis"

In [61]:
# sort values by ID which will allow them to be sudo random
result = result.sort_values(by=['ID'])

In [62]:
results2 = 0


for x in result:
    if()

LookForValue = ['Turbo']
outlier_free_list = [x for x in data[col] if (
    x==LookForValue)]


filtered_data = data.loc[data[col].isin(outlier_free_list)]

result.loc[data[col].isin(outlier_free_list)]

The amount of training records is: 13453
The amount of test records is: 2882
The amount of validation records is: 2882

In [62]:
# Split dataset

# data length
n = len(result)
# amount for testing/validation each
t = int(n*.15)
# amount for training
training = n-t*2

#create data sets
result.sort_values(by=['ID'])
training = result.head(training)
test = result.tail(t*2).head(t)
validation = result.tail(t)

# show values
print('The amount of training records is:', len(training))
print('The amount of test records is:', len(test))
print('The amount of validation records is:', len(validation))

In [63]:
training.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/TrainingData2.csv',index=False,line_terminator='\n')
test.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/TestData2.csv',index=False,line_terminator='\n')
validation.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/ValidationData2.csv',index=False,line_terminator='\n')
replace_table.to_csv('C:/Users/chris/Documents/School/Masters/zz_GIT/2022-msaai-500-final-project/data/sanitized/MakeModelReplaceTable.csv',index=False,line_terminator='\n')

As shown in the box plot above there is at least 1 super outlier that completely harms the data. Using a systematic attempt it was removed.

As we can see from the table and the box plot, although there are still outliers, the ones that massively skewed the data have been removed. In my opinion, more could have been removed from the bottom but we decided that it would be even on both the left and the right sides of the data. 
$\newline$
Upper percentile from base data = 0.99985
$\newline$
Lower percentile from base data = 0.00015
$\newline$
### In conclusion, this removal was required to make an accurate model for suggesting what a costumer should sell their car for in the market.